# Generated by Django 5.2.13 on 2026-04-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in login URL: /sso/login/<slug>/", unique=True
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("saml", "SAML 2.0"),
                            ("google_oauth", "Google OAuth 2.0"),
                            ("azure_oauth", "Microsoft Azure AD OAuth"),
                            ("oidc", "Custom OIDC / OAuth"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "saml_metadata_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload IdP metadata XML file (for SAML protocol)",
                        null=True,
                        upload_to="idp_metadata/",
                    ),
                ),
                (
                    "oauth_client_id",
                    models.CharField(
                        blank=True,
                        help_text="Client ID from Google Cloud Console or Azure Portal",
                        max_length=255,
                    ),
                ),
                (
                    "oauth_client_secret",
                    models.CharField(
                        blank=True,
                        help_text="Client Secret from Google Cloud Console or Azure Portal",
                        max_length=255,
                    ),
                ),
                (
                    "oidc_authorization_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="e.g. https://your-idp.com/oauth/authorize",
                    ),
                ),
                (
                    "oidc_token_endpoint",
                    models.URLField(
                        blank=True, help_text="e.g. https://your-idp.com/oauth/token"
                    ),
                ),
                (
                    "oidc_user_endpoint",
                    models.URLField(
                        blank=True, help_text="e.g. https://your-idp.com/oauth/userinfo"
                    ),
                ),
                (
                    "oidc_jwks_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="e.g. https://your-idp.com/.well-known/jwks.json",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity Provider",
                "verbose_name_plural": "Identity Providers",
            },
        ),
    ]
