# Generated by Django 5.2.13 on 2026-05-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprovider",
            name="oauth_allowed_domain",
            field=models.CharField(
                blank=True,
                help_text="Google OAuth: restrict to this Google Workspace domain, e.g. acme.com. Azure OAuth: the tenant ID (UUID) or domain, e.g. acme.onmicrosoft.com. Leave blank to allow any account (not recommended for production).",
                max_length=255,
            ),
        ),
    ]
