# Generated by Django 5.2.13 on 2026-05-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_oauth_allowed_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identityprovider",
            name="oauth_allowed_domain",
            field=models.CharField(
                blank=True,
                help_text="Restrict logins to this domain. SAML: email domain, e.g. acme.com. Google OAuth: Google Workspace domain, e.g. acme.com. Azure OAuth: Tenant ID (UUID) from Azure Portal. Leave blank to allow any account (not recommended for production).",
                max_length=255,
            ),
        ),
    ]
